[CmdletBinding()]
param(
	[string] $RegistryPath,
	[string] $SchemaPath,
	[string] $TablePath,
	[string] $CodexPath,
	[switch] $Check,
	[switch] $Write
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if ($Check -and $Write) { throw 'Choose -Check or -Write, not both.' }
$Root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
if (-not $RegistryPath) { $RegistryPath = Join-Path $Root 'design/combat-registry/registry.json' }
if (-not $SchemaPath) { $SchemaPath = Join-Path $Root 'design/combat-registry/schema.json' }
if (-not $TablePath) { $TablePath = Join-Path $Root 'docs/generated/combat-design-registry.md' }
if (-not $CodexPath) { $CodexPath = Join-Path $Root 'docs/generated/oathscar-codex-appendix.md' }

$TablePath = [IO.Path]::GetFullPath($TablePath)
$CodexPath = [IO.Path]::GetFullPath($CodexPath)
if ([string]::Equals($TablePath, $CodexPath, [StringComparison]::OrdinalIgnoreCase)) { throw 'Generated output paths must be distinct.' }

function Assert-CombatOutputNotSource {
	param([string[]] $ProtectedPaths)
	foreach ($ProtectedPath in $ProtectedPaths) {
		$FullProtectedPath = [IO.Path]::GetFullPath($ProtectedPath)
		if ([string]::Equals($TablePath, $FullProtectedPath, [StringComparison]::OrdinalIgnoreCase) -or
			[string]::Equals($CodexPath, $FullProtectedPath, [StringComparison]::OrdinalIgnoreCase)) {
			throw "Generated output path aliases a registry or canonical source: $FullProtectedPath"
		}
	}
}

Assert-CombatOutputNotSource @($RegistryPath, $SchemaPath)

$RequestedRegistryPath = $RegistryPath
$RequestedSchemaPath = $SchemaPath
. (Join-Path $PSScriptRoot 'Test-CombatRegistry.ps1') -SkipMain
$RegistryPath = $RequestedRegistryPath
$SchemaPath = $RequestedSchemaPath
$Validation = Test-CombatRegistry -RegistryPath $RegistryPath -SchemaPath $SchemaPath
if (-not $Validation.passed) { throw "Registry validation failed: $($Validation.errors -join '; ')" }
$Registry = Get-Content -LiteralPath $RegistryPath -Raw -Encoding UTF8 | ConvertFrom-Json
$SourceRepositoryRoot = (Resolve-Path (Join-Path (Split-Path -Parent $SchemaPath) '..\..')).Path
$CanonicalSources = @($Registry.definitions | ForEach-Object { Join-Path $SourceRepositoryRoot $_.source } | Select-Object -Unique)
Assert-CombatOutputNotSource $CanonicalSources

function ConvertTo-CombatMarkdownCell {
	param([string] $Value)
	return $Value.Replace('\', '\\').Replace('|', '\|')
}

function Get-CombatSourceLink {
	param($Record)
	$Name = [IO.Path]::GetFileName($Record.source)
	return "[source](../$Name$($Record.sourceAnchor))"
}

function ConvertTo-CombatMarkdownRow {
	param($Record)
	return '| ' + $Record.id + ' | ' + (ConvertTo-CombatMarkdownCell $Record.displayName) + ' | ' + $Record.kind + ' | ' + $Record.maturity + ' | ' + (ConvertTo-CombatMarkdownCell $Record.summary) + ' | ' + (Get-CombatSourceLink $Record) + ' |'
}

function ConvertTo-CombatUtf8Payload {
	param([string[]] $Lines)
	$Text = ($Lines -join "`n") + "`n"
	return (New-Object System.Text.UTF8Encoding($false)).GetBytes($Text)
}

function Test-CombatBytesEqual {
	param([byte[]] $Left, [byte[]] $Right)
	if ($Left.Length -ne $Right.Length) { return $false }
	for ($Index = 0; $Index -lt $Left.Length; $Index++) {
		if ($Left[$Index] -ne $Right[$Index]) { return $false }
	}
	return $true
}

$ById = @{}
foreach ($Record in $Registry.definitions) { $ById[$Record.id] = $Record }
$Ids = [string[]] @($ById.Keys)
[Array]::Sort($Ids, [StringComparer]::Ordinal)
$SortedRecords = @($Ids | ForEach-Object { $ById[$_] })
$OathscarRecords = @($SortedRecords | Where-Object { $_.id -eq 'order.oathscar' -or $_.id.StartsWith('order.oathscar.', [StringComparison]::Ordinal) })

$Header = @('| Stable ID | Display name | Kind | Maturity | Source-bound summary | Canonical source |', '| --- | --- | --- | --- | --- | --- |')
$TableLines = @(
	'# Combat Design Registry',
	'',
	'Generated from `design/combat-registry/registry.json` by `scripts/design/New-CombatRegistryAppendices.ps1`. Do not edit this file manually.',
	'Canonical product and technical documents remain the authority; maturity is a design state, not proof of implementation or playtest.',
	'',
	'## Definitions',
	''
) + $Header + @($SortedRecords | ForEach-Object { ConvertTo-CombatMarkdownRow $_ })
$CodexLines = @(
	'# Oathscar Codex Appendix',
	'',
	'Generated from `design/combat-registry/registry.json` by `scripts/design/New-CombatRegistryAppendices.ps1`. Do not edit this file manually.',
	'This appendix indexes source-bound Oathscar design entries; the linked canonical sections govern and unresolved tuning remains `TBD`.',
	'',
	'## Oathscar definitions',
	''
) + $Header + @($OathscarRecords | ForEach-Object { ConvertTo-CombatMarkdownRow $_ })

$Outputs = @(
	@{ Path = $TablePath; Bytes = (ConvertTo-CombatUtf8Payload $TableLines) },
	@{ Path = $CodexPath; Bytes = (ConvertTo-CombatUtf8Payload $CodexLines) }
)
if ($Write) {
	foreach ($Output in $Outputs) {
		[void][IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($Output.Path))
		[IO.File]::WriteAllBytes($Output.Path, [byte[]]$Output.Bytes)
		Write-Output "WROTE: $($Output.Path)"
	}
}
else {
	$Drift = New-Object 'System.Collections.Generic.List[string]'
	foreach ($Output in $Outputs) {
		if (-not [IO.File]::Exists($Output.Path)) { $Drift.Add("missing $($Output.Path)"); continue }
		if (-not (Test-CombatBytesEqual -Left ([byte[]]$Output.Bytes) -Right ([IO.File]::ReadAllBytes($Output.Path)))) { $Drift.Add("different bytes $($Output.Path)") }
	}
	if ($Drift.Count -gt 0) { throw "Generated combat registry drift: $($Drift -join '; '). Run New-CombatRegistryAppendices.ps1 -Write after reviewing the registry." }
	Write-Output "PASS: generated combat registry appendices match ($($SortedRecords.Count) definitions)"
}
