[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$Root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$Generator = Join-Path $Root 'scripts/design/New-CombatRegistryAppendices.ps1'
$Registry = Join-Path $Root 'design/combat-registry/registry.json'
$Schema = Join-Path $Root 'design/combat-registry/schema.json'
$FixtureRoot = Join-Path ([IO.Path]::GetTempPath()) ('AethelnCombatGeneration-' + [guid]::NewGuid().ToString('N'))
$Table = Join-Path $FixtureRoot 'combat-design-registry.md'
$Codex = Join-Path $FixtureRoot 'oathscar-codex-appendix.md'
$BadRegistry = Join-Path $FixtureRoot 'invalid-registry.json'
$AliasedRegistry = Join-Path $FixtureRoot 'registry-copy.json'
[void][IO.Directory]::CreateDirectory($FixtureRoot)
$Utf8 = New-Object System.Text.UTF8Encoding($false)

function Invoke-Generator {
	param([string[]] $ExtraArguments)
	$PreviousPreference = $ErrorActionPreference
	$ErrorActionPreference = 'Continue'
	try {
		$Output = @(& powershell.exe -NoProfile -File $Generator -RegistryPath $Registry -SchemaPath $Schema -TablePath $Table -CodexPath $Codex @ExtraArguments 2>&1 | ForEach-Object { "$_" })
		$ExitCode = $LASTEXITCODE
	}
	finally { $ErrorActionPreference = $PreviousPreference }
	return [pscustomobject]@{ ExitCode = $ExitCode; Output = ($Output -join "`n") }
}

function Assert-Result {
	param([string] $Name, [bool] $ExpectedSuccess, [string[]] $ExtraArguments)
	$Result = Invoke-Generator $ExtraArguments
	if (($Result.ExitCode -eq 0) -ne $ExpectedSuccess) { throw "${Name}: exit $($Result.ExitCode), output: $($Result.Output)" }
	Write-Output "PASS: $Name"
}

try {
Assert-Result -Name 'missing generated files fail the default drift check' -ExpectedSuccess $false -ExtraArguments @()
Assert-Result -Name 'write both generated appendices' -ExpectedSuccess $true -ExtraArguments @('-Write')
$FirstTable = [IO.File]::ReadAllBytes($Table)
$FirstCodex = [IO.File]::ReadAllBytes($Codex)
if ($FirstTable.Length -eq 0 -or $FirstCodex.Length -eq 0) { throw 'Generator wrote empty appendices.' }
foreach ($Bytes in @($FirstTable, $FirstCodex)) {
	if ($Bytes.Length -ge 3 -and $Bytes[0] -eq 239 -and $Bytes[1] -eq 187 -and $Bytes[2] -eq 191) { throw 'Generated appendices contain a UTF-8 BOM.' }
	if ([Array]::IndexOf($Bytes, [byte]13) -ge 0) { throw 'Generated appendices contain CR line endings.' }
}
Assert-Result -Name 'default drift check accepts exact generated bytes' -ExpectedSuccess $true -ExtraArguments @()
Assert-Result -Name 'explicit check accepts exact generated bytes' -ExpectedSuccess $true -ExtraArguments @('-Check')
Assert-Result -Name 'a second write is byte-for-byte deterministic' -ExpectedSuccess $true -ExtraArguments @('-Write')
if (-not [Linq.Enumerable]::SequenceEqual([byte[]]$FirstTable, [byte[]][IO.File]::ReadAllBytes($Table))) { throw 'Table output changed across identical writes.' }
if (-not [Linq.Enumerable]::SequenceEqual([byte[]]$FirstCodex, [byte[]][IO.File]::ReadAllBytes($Codex))) { throw 'Codex output changed across identical writes.' }
Write-Output 'PASS: byte-for-byte deterministic generation'

$TableText = [IO.File]::ReadAllText($Table, $Utf8)
$CodexText = [IO.File]::ReadAllText($Codex, $Utf8)
if ($TableText -notmatch 'combat\.resource\.health' -or $TableText -notmatch 'order\.oathscar\.peak\.oathbreak' -or $TableText -notmatch 'Canonical Intent') { throw 'Generated table omits required registry data.' }
if ($CodexText -notmatch 'order\.oathscar\.ability\.gate_step' -or $CodexText -match 'combat\.resource\.health') { throw 'Oathscar appendix selection is incorrect.' }
if ($TableText -notmatch '\.\./characters-and-factions\.md#' -or $CodexText -notmatch '\.\./characters-and-factions\.md#') { throw 'Generated source links are missing.' }
Write-Output 'PASS: table, codex selection, and canonical source links'

[IO.File]::WriteAllText($Table, ($TableText + "manual drift`n"), $Utf8)
$DriftBytes = [IO.File]::ReadAllBytes($Table)
Assert-Result -Name 'manual table edit fails drift check' -ExpectedSuccess $false -ExtraArguments @('-Check')
if (-not [Linq.Enumerable]::SequenceEqual([byte[]]$DriftBytes, [byte[]][IO.File]::ReadAllBytes($Table))) { throw 'Check mode rewrote a drifted table.' }
Write-Output 'PASS: check mode is read-only'
Assert-Result -Name 'write repairs drifted table' -ExpectedSuccess $true -ExtraArguments @('-Write')
[IO.File]::WriteAllText($Codex, ($CodexText + "manual drift`n"), $Utf8)
Assert-Result -Name 'manual codex edit fails drift check' -ExpectedSuccess $false -ExtraArguments @('-Check')
Assert-Result -Name 'write repairs drifted codex' -ExpectedSuccess $true -ExtraArguments @('-Write')

[IO.File]::WriteAllText($BadRegistry, '{"schemaId":"invalid"}', $Utf8)
$PreviousPreference = $ErrorActionPreference
$ErrorActionPreference = 'Continue'
try { $Invalid = @(& powershell.exe -NoProfile -File $Generator -RegistryPath $BadRegistry -SchemaPath $Schema -TablePath $Table -CodexPath $Codex -Write 2>&1 | ForEach-Object { "$_" }); $InvalidExit = $LASTEXITCODE }
finally { $ErrorActionPreference = $PreviousPreference }
if ($InvalidExit -eq 0) { throw "Invalid registry was generated: $($Invalid -join '; ')" }
if (-not [Linq.Enumerable]::SequenceEqual([byte[]]$FirstTable, [byte[]][IO.File]::ReadAllBytes($Table))) { throw 'Invalid registry modified the table.' }
if (-not [Linq.Enumerable]::SequenceEqual([byte[]]$FirstCodex, [byte[]][IO.File]::ReadAllBytes($Codex))) { throw 'Invalid registry modified the codex.' }
Write-Output 'PASS: invalid registry fails before modifying generated files'

[IO.File]::WriteAllBytes($AliasedRegistry, [IO.File]::ReadAllBytes($Registry))
$ProtectedBytes = [IO.File]::ReadAllBytes($AliasedRegistry)
$PreviousPreference = $ErrorActionPreference
$ErrorActionPreference = 'Continue'
try { $AliasOutput = @(& powershell.exe -NoProfile -File $Generator -RegistryPath $AliasedRegistry -SchemaPath $Schema -TablePath $AliasedRegistry -CodexPath $Codex -Write 2>&1 | ForEach-Object { "$_" }); $AliasExit = $LASTEXITCODE }
finally { $ErrorActionPreference = $PreviousPreference }
if ($AliasExit -eq 0 -or -not [Linq.Enumerable]::SequenceEqual([byte[]]$ProtectedBytes, [byte[]][IO.File]::ReadAllBytes($AliasedRegistry))) {
	throw "Aliased output overwrote the registry input: $($AliasOutput -join '; ')"
}
Write-Output 'PASS: output path cannot overwrite registry input'
}
finally {
	if (Test-Path -LiteralPath $FixtureRoot) {
		$ResolvedFixtureRoot = (Resolve-Path -LiteralPath $FixtureRoot).Path
		$ResolvedTempRoot = (Resolve-Path -LiteralPath ([IO.Path]::GetTempPath())).Path.TrimEnd([IO.Path]::DirectorySeparatorChar) + [IO.Path]::DirectorySeparatorChar
		if (-not $ResolvedFixtureRoot.StartsWith($ResolvedTempRoot, [StringComparison]::OrdinalIgnoreCase) -or
			-not [IO.Path]::GetFileName($ResolvedFixtureRoot).StartsWith('AethelnCombatGeneration-', [StringComparison]::Ordinal)) {
			throw 'Fixture cleanup target escaped the owned temporary directory.'
		}
		Remove-Item -LiteralPath $ResolvedFixtureRoot -Recurse -Force
	}
}
